### ISSUE TITLE
Couple of typo's to correct

### ISSUE THREAD

**Issue by sscotter** [dellock6/veeam-iac-lab#1]
Thanks for the repo. The ubuntu files have been very useful in getting me started creating a VMware Template. I have however spotted a couple of typos which could do with fixing for anyone that follows in my foot steps.

1) Filename incorrect
Your blog https://www.virtualtothecore.com/my-automated-lab-project-2-create-a-ubuntu-template-in-vmware-vsphere-with-packer/ instructs the user to execute `packer build -force -on-error=ask -var-file ubuntu2204.pkrvars.hcl -var-file vsphere.pkrvars.hcl ubuntu2204.pkr.hcl`, however `ubuntu2204.pkrvars.hcl` doesn't exist in the repo. I think you need to either update the command mentioned in the blog to reference `variables.pkrvarsubuntu2204.hcl` or update the repo and rename `variables.pkrvarsubuntu2204.hcl` to `ubuntu2204.pkrvars.hcl` (I did the latter locally).

2) Backtick instead of single quote in setup_ubuntu2204.sh
In line 58 or  `setup_ubuntu2204.sh` the command 
```echo `> modifying grub` ```
should be
```echo '> modifying grub'```
The typo results in the error `grub: command not found` when building. (took me ages to track that one down 🤣)
![2024-04-26--132658--zoc--colony_(Standard-With-Keys zoc)_nimda@colony_~test--I6lYnnzLeL](https://github.com/dellock6/veeam-iac-lab/assets/12397498/d5131a6a-0e54-4862-93a9-e58b4e7cb4c9)

Thanks again for the repo!

**Comment by dellock6** [comment]
Hi Stephen,
thanks for the notes, probably some bad copy/paste lead to these errors. I edited both files in the repo.
Thanks again!

**Comment by sscotter** [comment]
Thanks!👍
